; PCM Loop -> A2DP Source
; Placa: DFRobot FireBeetle 2 ESP32-E

[env:firebeetle2]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino

monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

; LittleFS na particao spiffs + tabela customizada
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; Bibliotecas do pschatzmann direto do GitHub (versoes mais atuais que o registry)
lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/ESP32-A2DP.git

build_flags =
    -DCORE_DEBUG_LEVEL=1



